---
- name: Create filesystem for /var/lib/origin/openshift.local.volumes
  filesystem:
      fstype: xfs
      dev: /dev/sdc

- name: Create local volumes directory
  file:
      path: /var/lib/origin/openshift.local.volumes
      state: directory
      recurse: yes

- name: Create fstab entry
  mount:
      name: /var/lib/origin/openshift.local.volumes
      src: '/dev/sdc'
      fstype: xfs
      opts: gquota
      state: present

- name: Mount fstab entry
  mount:
      name: /var/lib/origin/openshift.local.volumes
      src: '/dev/sdc'
      fstype: xfs
      opts: gquota
      state: mounted
