# These are the default variables across all playbooks. This directory should contain
# all files referenced by the playbook when running in a docker container. To reference
# a file, assume the path is the same as playbooks/files or use a relative path to the
# playbook for lookup(...).
#
# This ensures that a relatively standard layout is used both inside and outside
# of a containerized image.

# Package and target versions

deployment_type: origin
ansible_pkg_mgr: yum
openshift_version: 1.4.0

# URLs and certs

openshift_master_cluster_public_hostname: api.ci.openshift.org
openshift_master_cluster_hostname: internal-master.ci.openshift.org
public_hosted_zone: ci.openshift.org
dns_managed_zone: origin-ci-ocp-public-dns
wildcard_zone: svc.ci.openshift.org
console_port: 443
internal_console_port: 8443
openshift_master_api_port: "8443"
openshift_master_console_port: "8443"
openshift_master_public_api_url: "https://api.ci.openshift.org"
openshift_master_public_console_url: "https://api.ci.openshift.org/console"
openshift_node_port_range: 30000-32000

# Authentication and authorization

# By default reads the identity-providers.json file from the data directory (since identity providers often include secrets).
openshift_master_identity_providers: "{{ (lookup('file', 'files/identity-providers.json' ) | default('{\"items\":[]}') | from_json).get('items') }}"
# A set of initial roles to bootstrap the cluster with to bypass the need to copy the cluster-admin configuration file.
# Set to empty array for no defaults.
provision_role_mappings: [{'user': 'my-user', 'role': 'cluster-admin'}]

# Paths on the local system for the certificate files. If empty, self-signed
# certificate will be generated.
provision_master_https_cert_file: "ssl.crt"
provision_master_https_key_file: "ssl.key"

# Post config setting sizes

# Configuration for cluster sizes
openshift_hosted_router_replicas: 1
openshift_hosted_registry_replicas: 1
# Must be true if provision_gce_instance_group_size_node_infra is zero.
openshift_schedulable: True

# GCE provisioning info

# Project ID and zone settings for Google Cloud
gce_project_id: openshift-gce-devel
gce_region_name: us-central1
gce_zone_name: us-central1-a
# A GCE service account JSON file that has sufficient permission to provision all instances
# on the cluster and to also act as the cloud provider (create service load balancers, set
# routes, provision PVs). You may restrict the permission of the account after creation.
gce_service_account_keyfile: "gce.json"
# The path to the private key on the host. If using the Docker image, this is set up by
# default to match "ssh-privatekey" and "ssh-publickey" from the data directory. If those
# files are not present, a unique key pair is generated and added to the project.
gce_ssh_private_key: /home/cloud-user/.ssh/google_compute_engine
# GCE service account JSON file that must have permission to read and write from the bucket
# named by provision_gce_registry_gcs_bucket. May be the same as gce_service_account_keyfile, but
# not recommended.
gcs_registry_keyfile: "gcs-registry.json"
# Required to be external unless a custom inventory is used
inventory_ip_type: external

# Extra tags to add to each instance template, must start with a comma
gce_extra_tags_master: ",preserve"
gce_extra_tags_node: ",preserve"
gce_extra_tags_node_infra: ",preserve"

# The sizes of instances to create
provision_gce_machine_type_master: n1-standard-2
provision_gce_machine_type_node: n1-standard-2
provision_gce_machine_type_node_infra: n1-standard-2

# The instance sizes of each group. If node-infra is 0, you must set
# provision_gce_router_network_instance_group to ig-m
provision_gce_instance_group_size_master: 1
provision_gce_instance_group_size_node_infra: 0
provision_gce_instance_group_size_node: 2

# The size of disks attached to each node. The Docker disk is for images and containers, the OpenShift
# disk is for empty dir volumes and local storage.
provision_gce_disk_size_node_docker: 25
provision_gce_disk_size_node_openshift: 50

# Provision prefix is a common identifier placed at the beginning of ALL GCE resource names
# to allow multiple clusters to be deployed in one GCE project.
provision_prefix: my-cluster-
# Network name is a configuration parameter that is used by the cloud provider to provision
# service load balancers.
gce_network_name: "my-cluster-ocp-network"

# An image that is registered with the appropriate subscriptions (for RHEL) or
# Red Hat.
provision_gce_registered_image: rhel-guest-image-7-2-20160302-0-x86-64-registered

# The name of a GCS bucket to create for the registry in the current project
provision_gce_registry_gcs_bucket: my-cluster-registry-storage

# Control which node group router traffic is targeted at. You may set this to ig-m to point
# to the master.
provision_gce_router_network_instance_group: ig-m # or: ig-i

# Provide a startup script file to the GCE instances
provision_gce_startup_script_file:
# Provide userdata to the gce instances
provision_gce_user_data_file:
