---
- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: masters, etcd, nodes, cluster_hosts, infra_nodes
    openshift_node_labels:
      role: infra
      subrole: master
  with_items: "{{ groups['tag_ocp-master'] }}"

- name: Add a master to the primary masters group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: primary_master
    openshift_node_labels:
      role: infra
      subrole: master
  with_items: "{{ groups['tag_ocp-master'].0 }}"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: nodes, cluster_hosts, schedulable_nodes, infra_nodes
    openshift_node_labels:
      role: infra
      subrole: worker
  with_items: "{{ groups['tag_ocp-infra-node'] | default([]) }}"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: nodes, cluster_hosts, schedulable_nodes, app_nodes
    openshift_node_labels:
      role: app
  with_items: "{{ groups['tag_ocp-node'] | default([])  }}"

- name: Mark all bootstrap nodes with the right Ansible flag
  set_fact:
    openshift_node_bootstrap: True
  delegate_to: "{{ hostvars[item].gce_name }}"
  delegate_facts: True
  with_items: "{{ groups['tag_ocp-bootstrap'] | default([])  }}"
