# This playbook converges the cluster to the desired state

- hosts: localhost
  connection: local
  roles:
    - gce-instance-groups

- hosts: nodes
  roles:
    - gce-docker-storage-setup
    - gce-cloudconfig
    - frequent-log-rotation

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml

- hosts: masters
  gather_facts: no
  roles:
    - master-http-proxy

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

- hosts: primary_master
  gather_facts: no
  tasks:
    - name: Retrieve cluster configuration
      fetch:
        src: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
        dest: "/tmp/"
        flat: yes

- hosts: masters
  gather_facts: no
  roles:
    - role: gce-master-bootstrap
      when: openshift_master_bootstrap_enabled | default(False)

- hosts: primary_master
  gather_facts: no
  roles:
    - openshift-roles
    - master-validate

- hosts: localhost
  tasks:
    - name: Validate the public address from outside the cluster
      uri:
        url: "https://{{ openshift_master_cluster_public_hostname }}:{{ console_port }}/healthz/ready"
        validate_certs: False
        method: GET
      register: resp
      until: resp.status == 200
      retries: 6
      delay: 5

- hosts: app_nodes
  gather_facts: no
  roles:
    - gce-node-restrict-metadata
    - node-emptydir-quota
