# This playbook converges the cluster to the desired state

- hosts: localhost
  connection: local
  roles:
    - gce-instance-groups

- hosts: cluster_hosts
  roles:
    - gce-cluster-variables
    - gce-docker-storage-setup
    - gce-cloudconfig
    - frequent-log-rotation

# 3.7 requires std_include in order to invoke os_firewall (for now). Conditionally include it so
# we don't break for older versions. Should be removed when os_firewall becomes a module.
- hosts: localhost
  tasks:
    - stat: path=/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/std_include.yml
      register: std_include
      become: no
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/initialize_groups.yml
- include: /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/std_include.yml
  when: hostvars['localhost']['std_include'].stat.exists

- hosts: masters
  gather_facts: no
  roles:
    - master-http-proxy
    - role: /usr/share/ansible/openshift-ansible/roles/os_firewall
      os_firewall_allow:
        - service: master http proxy
          port: 8080/tcp

- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

- hosts: primary_master
  gather_facts: no
  tasks:
    - name: Retrieve cluster configuration
      fetch:
        src: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
        dest: "/tmp/"
        flat: yes

- hosts: primary_master
  gather_facts: no
  roles:
    - openshift-roles
    - master-validate

- hosts: localhost
  tasks:
    - name: Validate the public address from outside the cluster
      uri:
        url: "https://{{ openshift_master_cluster_public_hostname }}:{{ console_port }}/healthz/ready"
        validate_certs: False
        method: GET
      register: resp
      until: resp.status == 200
      retries: 6
      delay: 5

- hosts: infra_nodes
  gather_facts: no
  roles:
    - role: /usr/share/ansible/openshift-ansible/roles/os_firewall
      os_firewall_allow:
        - service: router liveness probe
          port: 1936/tcp

- hosts: app_nodes
  gather_facts: no
  roles:
    - gce-node-restrict-metadata
    - node-emptydir-quota
